import os
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def interpret_project(project_type):

    prompt = f"""
You are an expert software architect.

Convert the following project idea into a structured JSON format.

Project:
{project_type}

Return ONLY valid JSON. No explanation.

Format:
{{
  "name": "project-name",
  "frontend": [
    {{"path": "frontend/pages/index.js", "description": "homepage UI"}},
    {{"path": "frontend/components/Navbar.js", "description": "navigation bar"}}
  ],
  "backend": [
    {{"path": "backend/api/app.js", "description": "main API"}},
    {{"path": "backend/api/orders.js", "description": "orders endpoint"}}
  ],
  "database": [
    {{"path": "database/schema.sql", "description": "database schema"}}
  ]
}}
"""

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {"role": "system", "content": "You are a software architect."},
            {"role": "user", "content": prompt}
        ],
    )

    return response.choices[0].message.content
    
    
    def interpret_project_files(project_type):
        return {
            "README.md": f"# {project_type}\n\nGenerated by Atlas AI\n",

            "frontend/pages/index.js": """
export default function Home() {
  return (
    <div>
      <h1>🍪 Cookie Ordering App</h1>
      <p>Welcome! Your app is ready.</p>
    </div>
  )
}
""",

        "backend/api/app.js": """
export default function handler(req, res) {
  res.status(200).json({ message: "Backend is running 🚀" })
}
""",

        "database/schema.sql": """
CREATE TABLE cookies (
  id SERIAL PRIMARY KEY,
  name TEXT,
  price NUMERIC,
  created_at TIMESTAMP DEFAULT NOW()
);
"""
    }
