import discord
import asyncio
import json

from github_tools import create_or_update_repo
from atlas_brain import interpret_project, interpret_project


# -----------------------------
# SAFE DISCORD MESSAGE SPLITTER
# -----------------------------
async def send_split_message(channel, content, chunk_size=1900):

    for i in range(0, len(content), chunk_size):
        await channel.send(content[i:i+chunk_size])


# -----------------------------
# GENERATE FILES FROM AI JSON
# -----------------------------
def generate_files_from_json(project_json):

    files = {}

    try:
        data = json.loads(project_json)

        # README
        files["README.md"] = f"# {data.get('name', 'atlas-project')}\n\nGenerated by Atlas AI\n"

        # FRONTEND FILES
        for item in data.get("frontend", []):
            path = item["path"]
            files[path] = f"// {item['description']}\n\nexport default function Page() {{\n  return <div>{item['description']}</div>\n}}"

        # BACKEND FILES
        for item in data.get("backend", []):
            path = item["path"]
            files[path] = f"// {item['description']}\n\nmodule.exports = (req, res) => {{\n  res.json({{'message': '{item['description']}'}})\n}}"

        # DATABASE FILES
        for item in data.get("database", []):
            path = item["path"]
            files[path] = f"-- {item['description']}\n\nCREATE TABLE example(id SERIAL PRIMARY KEY);"

    except Exception as e:
        files["error.txt"] = str(e)

    return files


# -----------------------------
# MAIN BUILD PIPELINE
# -----------------------------
async def run_build_pipeline(bot, ctx, project_type):

    guild = ctx.guild

    pm = discord.utils.get(guild.text_channels, name="pm")
    architect = discord.utils.get(guild.text_channels, name="architect")
    plans = discord.utils.get(guild.text_channels, name="architect-plans")
    dev = discord.utils.get(guild.text_channels, name="dev")
    qa = discord.utils.get(guild.text_channels, name="qa")
    security = discord.utils.get(guild.text_channels, name="security")
    updates = discord.utils.get(guild.text_channels, name="project-updates")

    # -----------------------------
    # PM
    # -----------------------------
    if pm:
        await pm.send("📋 Build request received: " + project_type)

    # -----------------------------
    # ARCHITECT
    # -----------------------------
    if architect:
        await architect.send("🧠 Designing system with AI...")

    project_json = interpret_project(project_type)

    if plans:
        await send_split_message(plans, project_json)

    await asyncio.sleep(1)

    # -----------------------------
    # DEV
    # -----------------------------
    if dev:
        await dev.send("👨‍💻 Generating real project files...")

    files = generate_files_from_json(project_type)

    repo_name, version = create_or_update_repo(project_type, files)

    await asyncio.sleep(1)

    # -----------------------------
    # QA
    # -----------------------------
    if qa:
        await qa.send("🧪 Running automated tests...")

    # -----------------------------
    # SECURITY
    # -----------------------------
    if security:
        await security.send("🔐 Running security scan...")

    # -----------------------------
    # UPDATES
    # -----------------------------
    if updates:
        embed = discord.Embed(
            title="📦 Project Generated",
            color=discord.Color.green()
        )

        embed.add_field(name="Project", value=project_type, inline=False)
        embed.add_field(name="Repository", value=repo_name, inline=False)
        embed.add_field(name="Version", value=version, inline=False)

        await updates.send(embed=embed)

    await ctx.send("🚀 Build complete → " + repo_name)
