import discord
import asyncio
import json

from github_tools import create_or_update_repo
from atlas_brain import interpret_project


# -----------------------------
# 🔥 SESSION MEMORY
# -----------------------------
user_sessions = {}

def save_repo(user_id, repo_name):
    user_sessions[user_id] = repo_name

def get_repo(user_id):
    return user_sessions.get(user_id)


# -----------------------------
# SAFE DISCORD MESSAGE SPLITTER
# -----------------------------
async def send_split_message(channel, content, chunk_size=1900):
    for i in range(0, len(content), chunk_size):
        await channel.send(content[i:i+chunk_size])


# -----------------------------
# 🔥 GENERATE FILES FROM AI JSON
# -----------------------------
def generate_files_from_json(project_json):

    files = {}

    try:
        data = json.loads(project_json)

        # -----------------------------
        # README
        # -----------------------------
        files["README.md"] = f"# {data.get('name', 'atlas-project')}\n\nGenerated by Atlas AI\n"

        # -----------------------------
        # 🔥 CORE BACKEND (REQUIRED FOR RAILWAY)
        # -----------------------------
        files["backend/app.js"] = """const express = require("express");
const app = express();

app.get("/", (req, res) => {
  res.send("Atlas app is live 🚀");
});

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log("Server running on port " + PORT);
});
"""

        files["backend/package.json"] = """{
  "name": "atlas-app",
  "version": "1.0.0",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "express": "^4.18.2"
  }
}"""

        # -----------------------------
        # 🔥 START SCRIPT (CRITICAL)
        # -----------------------------
        files["start.sh"] = """#!/bin/bash
cd backend
npm install
npm start
"""

        # -----------------------------
        # FRONTEND FILES
        # -----------------------------
        for item in data.get("frontend", []):
            path = item["path"]
            files[path] = f"""// {item['description']}

export default function Page() {{
  return <div>{item['description']}</div>
}}"""

        # -----------------------------
        # BACKEND FILES (AI GENERATED)
        # -----------------------------
        for item in data.get("backend", []):
            path = item["path"]
            files[path] = f"""// {item['description']}

module.exports = (req, res) => {{
  res.json({{'message': '{item['description']}'}})
}}"""

        # -----------------------------
        # DATABASE FILES
        # -----------------------------
        for item in data.get("database", []):
            path = item["path"]
            files[path] = f"""-- {item['description']}

CREATE TABLE example(id SERIAL PRIMARY KEY);"""

    except Exception as e:
        files["error.txt"] = str(e)

    return files


# -----------------------------
# 🚀 MAIN BUILD PIPELINE
# -----------------------------
async def run_build_pipeline(bot, ctx, project_type):

    guild = ctx.guild

    pm = discord.utils.get(guild.text_channels, name="pm")
    architect = discord.utils.get(guild.text_channels, name="architect")
    plans = discord.utils.get(guild.text_channels, name="architect-plans")
    dev = discord.utils.get(guild.text_channels, name="dev")
    qa = discord.utils.get(guild.text_channels, name="qa")
    security = discord.utils.get(guild.text_channels, name="security")
    updates = discord.utils.get(guild.text_channels, name="project-updates")

    # PM
    if pm:
        await pm.send("📋 Build request received: " + project_type)

    # ARCHITECT
    if architect:
        await architect.send("🧠 Designing system with AI...")

    project_json = interpret_project(project_type)

    if plans:
        await send_split_message(plans, project_json)

    await asyncio.sleep(1)

    # DEV
    if dev:
        await dev.send("👨‍💻 Generating real project files...")

    files = generate_files_from_json(project_json)

    # 🔥 BUILD (non-blocking)
    repo_name, version = await asyncio.to_thread(
        create_or_update_repo,
        project_type,
        files
    )

    # SAVE FOR UPDATE MODE
    save_repo(ctx.author.id, repo_name)

    await asyncio.sleep(1)

    # QA
    if qa:
        await qa.send("🧪 Running automated tests...")

    # SECURITY
    if security:
        await security.send("🔐 Running security scan...")

    # UPDATES
    if updates:
        embed = discord.Embed(
            title="📦 Project Generated",
            color=discord.Color.green()
        )

        embed.add_field(name="Project", value=project_type, inline=False)
        embed.add_field(name="Repository", value=repo_name, inline=False)
        embed.add_field(name="Version", value=version, inline=False)

        await updates.send(embed=embed)

    await ctx.send("🚀 Build complete → " + repo_name)


# -----------------------------
# 🔁 UPDATE PIPELINE
# -----------------------------
async def run_update_pipeline(bot, ctx, request):

    repo_name = get_repo(ctx.author.id)

    if not repo_name:
        await ctx.send("❌ No project found. Run !build first.")
        return

    await ctx.send("🧠 Updating your project...")

    project_json = interpret_project(request)

    files = generate_files_from_json(project_json)

    # 🔥 UPDATE MODE
    repo_name, version = await asyncio.to_thread(
        create_or_update_repo,
        request,
        files,
        repo_name
    )

    await ctx.send(f"🔁 Project updated → {repo_name}")