import os
from github import Github

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_USER = os.getenv("GITHUB_USER")

g = Github(GITHUB_TOKEN)


def create_or_update_repo(project_type):

    repo_name = "atlas-" + project_type.replace(" ", "-").lower()

    user = g.get_user()

    try:
        repo = user.get_repo(repo_name)
        version = "v2"
    except:
        repo = user.create_repo(repo_name)
        version = "v1"

    files = {
        "README.md": f"# {repo_name}\n\nGenerated by Atlas\n",

        "package.json": """
{
  "name": "atlas-app",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest",
    "@supabase/supabase-js": "latest",
    "stripe": "latest"
  }
}
""",

        "pages/index.js": """
export default function Home() {
  return (
    <div style={{padding:40}}>
      <h1>Atlas Generated App</h1>
      <p>Your project is ready.</p>
    </div>
  )
}
""",

        "lib/supabase.js": """
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_KEY

export const supabase = createClient(supabaseUrl, supabaseKey)
"""
    }

    for path, content in files.items():

        try:
            existing = repo.get_contents(path)

            repo.update_file(
                existing.path,
                "Atlas automated update",
                content,
                existing.sha
            )

        except:
            repo.create_file(
                path,
                "Atlas automated project build",
                content
            )

    return repo_name, version