import os
import requests
import re
import time
import base64

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME")

headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}


def slugify_project(project_type):
    cleaned = project_type.lower()
    cleaned = cleaned.replace("with payments", "")
    cleaned = cleaned.replace("app", "")
    cleaned = cleaned.replace("application", "")
    cleaned = re.sub(r"[^a-z0-9\s]", "", cleaned)
    cleaned = re.sub(r"\s+", "-", cleaned).strip("-")
    return f"atlas-{cleaned}"


# ✅ CREATE REPO
def create_repo(repo_name):

    r = requests.post(
        "https://api.github.com/user/repos",
        json={
            "name": repo_name,
            "private": False
        },
        headers=headers
    )

    print("CREATE REPO:", r.status_code)

    if r.status_code not in [201, 422]:
        print("❌ Repo creation failed:", r.text)
        return False

    print("Repo created ✅")
    return True


# 🔥 GET FILE SHA (KEY FOR UPDATES)
def get_file_sha(repo_name, path):

    url = f"https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/contents/{path}"

    r = requests.get(url, headers=headers)

    if r.status_code == 200:
        return r.json().get("sha")

    return None


# 🔥 CREATE OR UPDATE FILE (SMART)
def create_or_update_file(repo_name, path, content):

    path = path.lstrip("/").replace("[", "").replace("]", "")

    url = f"https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/contents/{path}"

    encoded = base64.b64encode(content.encode()).decode()

    sha = get_file_sha(repo_name, path)

    data = {
        "message": f"{'Update' if sha else 'Add'} {path}",
        "content": encoded,
        "branch": "main"
    }

    if sha:
        data["sha"] = sha  # 🔥 THIS IS THE MAGIC

    r = requests.put(url, json=data, headers=headers)

    print(f"{path} → {r.status_code}")

    return r.status_code in [200, 201]


# 🔁 UPDATE EXISTING REPO
def update_repo(repo_name, files):

    success = 0

    for path, content in files.items():
        if create_or_update_file(repo_name, path, content):
            success += 1

        time.sleep(0.1)

    print(f"🔁 Updated {success}/{len(files)} files")

    return success


# 🚀 MAIN (NOW SUPPORTS UPDATE MODE)
def create_or_update_repo(project_type, files, existing_repo=None):

    # 🔁 UPDATE MODE
    if existing_repo:
        print("🔁 Updating existing repo:", existing_repo)
        update_repo(existing_repo, files)
        return existing_repo, "updated"

    # 🆕 CREATE MODE
    repo_name = f"{slugify_project(project_type)}-{int(time.time())}"

    if not create_repo(repo_name):
        return repo_name, "failed"

    success = 0

    # 🔥 Create README first (ensures repo is initialized cleanly)
    create_or_update_file(
        repo_name,
        "README.md",
        f"# {project_type}\n\nGenerated by Atlas AI"
    )

    for path, content in files.items():

        ok = create_or_update_file(repo_name, path, content)

        if ok:
            success += 1
        else:
            print("❌ Failed on:", path)
            break

        time.sleep(0.1)

    print(f"✅ Uploaded {success}/{len(files)} files")

    return repo_name, "v1" if success > 0 else "failed"