name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 New commit pushed to atlas-control-bot by ${{ github.actor }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
